# Generated by Django 4.2.27 on 2025-12-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Jami xabarlar')),
                ('total_users', models.IntegerField(default=0, verbose_name='Jami foydalanuvchilar')),
                ('last_message_date', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi xabar')),
                ('bot_started_at', models.DateTimeField(auto_now_add=True, verbose_name='Bot ishga tushgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Bot statistika',
                'verbose_name_plural': 'Bot statistika',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram User ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiya')),
                ('message_text', models.TextField(verbose_name='Xabar matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('is_sent_to_admin', models.BooleanField(default=True, verbose_name='Adminga yuborildi')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='bot_message_created_bc79d0_idx'), models.Index(fields=['telegram_user_id'], name='bot_message_telegra_991cdc_idx')],
            },
        ),
    ]
